[pytest]
testpaths = src/roboclean_bt/test src/roboclean_navigation/test src/roboclean_driver/test src/roboclean_sensors/test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short
norecursedirs = .git __pycache__
